spring.application.name=cbs-core

server.port=8080

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=UTPAL
spring.datasource.password=UtpalOracle123

spring.h2.console.enabled=false

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Y2JzLXNlY3JldC1rZXktZm9yLWRlbW8tb25seS1kb250LXVzZS1pbi1wcm9k
jwt.expiration=86400000

logging.level.com.cbs=DEBUG
